version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend/todolist
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=${BACKEND_URL:-http://localhost:5000}/api
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - ./backend:/app 